# var
@baseUrl = http://localhost:3000
@user1 = { "username": "a", "password": "a" }
@user2 = { "username": "b", "password": "b" }
@user3 = { "username": "c", "password": "c" }

###
GET {{baseUrl}}

### signup
POST {{baseUrl}}/signup
Content-Type: application/json

{{user2}}

### signup
POST {{baseUrl}}/signup
Content-Type: application/json

{{user3}}

### login
POST {{baseUrl}}/login
Content-Type: application/json

{{user2}}

# section user route
### get users
GET {{baseUrl}}/user

### get user message
GET {{baseUrl}}/user/1/2

### post send message
POST {{baseUrl}}/user/1/2
Content-Type: application/json

# to note 'no , at last end'
{
  "message": "msg 3"
}

### get user
GET {{baseUrl}}/user/4 HTTP/1.1

### delete add friend
POST  {{baseUrl}}/user/1/friend HTTP/1.1
Content-Type: application/json

{
  "friendId": 3
}

### delete remove friend
DELETE {{baseUrl}}/user/1/friend
Content-Type: application/json

{
  "friendId": 3
}
